// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asyauqi15/payslip-system/internal/usecase/payslip (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_usecase.go -package=mock github.com/asyauqi15/payslip-system/internal/usecase/payslip Usecase
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/asyauqi15/payslip-system/pkg/openapi/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetPayslip mocks base method.
func (m *MockUsecase) GetPayslip(arg0 context.Context, arg1 int64) (*v1.PayslipResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayslip", arg0, arg1)
	ret0, _ := ret[0].(*v1.PayslipResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayslip indicates an expected call of GetPayslip.
func (mr *MockUsecaseMockRecorder) GetPayslip(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayslip", reflect.TypeOf((*MockUsecase)(nil).GetPayslip), arg0, arg1)
}
