// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for PostEmployeeAttendanceJSONBodyAttendanceType.
const (
	CheckIn  PostEmployeeAttendanceJSONBodyAttendanceType = "check_in"
	CheckOut PostEmployeeAttendanceJSONBodyAttendanceType = "check_out"
)

// AttendancePeriodRequest defines model for AttendancePeriodRequest.
type AttendancePeriodRequest struct {
	EndDate   openapi_types.Date `json:"end_date"`
	StartDate openapi_types.Date `json:"start_date"`
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// DefaultErrorResponse defines model for DefaultErrorResponse.
type DefaultErrorResponse struct {
	Error struct {
		Message string `json:"message"`
	} `json:"error"`
}

// OvertimeRequest defines model for OvertimeRequest.
type OvertimeRequest struct {
	Date      openapi_types.Date `json:"date"`
	EndTime   time.Time          `json:"end_time"`
	StartTime time.Time          `json:"start_time"`
}

// PayslipResponse defines model for PayslipResponse.
type PayslipResponse struct {
	BaseSalary      *int    `json:"base_salary,omitempty"`
	OvertimePayment *int    `json:"overtime_payment,omitempty"`
	PayrollId       *string `json:"payroll_id,omitempty"`
	ProratedSalary  *int    `json:"prorated_salary,omitempty"`
	Reimbursements  *[]struct {
		Amount      *int    `json:"amount,omitempty"`
		Date        *string `json:"date,omitempty"`
		Description *string `json:"description,omitempty"`
	} `json:"reimbursements,omitempty"`
	TotalTakeHome *int `json:"total_take_home,omitempty"`
}

// ReimbursementRequest defines model for ReimbursementRequest.
type ReimbursementRequest struct {
	Amount      int                `json:"amount"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
}

// PostAdminPayrollsJSONBody defines parameters for PostAdminPayrolls.
type PostAdminPayrollsJSONBody struct {
	AttendancePeriodId openapi_types.UUID `json:"attendance_period_id"`
}

// GetAdminPayslipsSummaryParams defines parameters for GetAdminPayslipsSummary.
type GetAdminPayslipsSummaryParams struct {
	PayrollId string `form:"payroll_id" json:"payroll_id"`
}

// PostEmployeeAttendanceJSONBody defines parameters for PostEmployeeAttendance.
type PostEmployeeAttendanceJSONBody struct {
	AttendanceType PostEmployeeAttendanceJSONBodyAttendanceType `json:"attendance_type"`
}

// PostEmployeeAttendanceJSONBodyAttendanceType defines parameters for PostEmployeeAttendance.
type PostEmployeeAttendanceJSONBodyAttendanceType string

// GetEmployeePayslipParams defines parameters for GetEmployeePayslip.
type GetEmployeePayslipParams struct {
	PayrollId string `form:"payroll_id" json:"payroll_id"`
}

// PostAdminAttendancePeriodsJSONRequestBody defines body for PostAdminAttendancePeriods for application/json ContentType.
type PostAdminAttendancePeriodsJSONRequestBody = AttendancePeriodRequest

// PostAdminPayrollsJSONRequestBody defines body for PostAdminPayrolls for application/json ContentType.
type PostAdminPayrollsJSONRequestBody PostAdminPayrollsJSONBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthRequest

// PostEmployeeAttendanceJSONRequestBody defines body for PostEmployeeAttendance for application/json ContentType.
type PostEmployeeAttendanceJSONRequestBody PostEmployeeAttendanceJSONBody

// PostEmployeeOvertimeJSONRequestBody defines body for PostEmployeeOvertime for application/json ContentType.
type PostEmployeeOvertimeJSONRequestBody = OvertimeRequest

// PostEmployeeReimbursementJSONRequestBody defines body for PostEmployeeReimbursement for application/json ContentType.
type PostEmployeeReimbursementJSONRequestBody = ReimbursementRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXTW/jNhP+KwTf96iNvd1L4Vu23S5SFGiQFOghMAxGGlvcSKQyHGZhBP7vBT9kyxJl",
	"K94G6E0ih/P1PDNDvvJc141WoMjwxSs3eQm18J/XRKAKoXK4BZS6uINnC4bcVoO6ASQJXhBUsSoEgfte",
	"a6wF8QX3CxmnbQN8wQ2hVBu+y7ghgTRVfJdxhGcrEQq+eOiezQ5Wl/tj+vEb5OSsXFsqR/1thDHfNRbu",
	"e+CfNYBK1JDY7Hmzl8wOGsd9MY1WBobOiDwHY1akn0AlHUJYI5hyVKLn1ZG+/umUe7/CWtiKviBqHHcT",
	"3PZwuQZjxGZCslrBoQc9wWAo5eifL85uDaO4Tuago47TNBD+4FdHWfuWM72woisdPR03UtHeiq2pZDOO",
	"yKMwsDKiErjtpF8qgg2g06BjvlaN2NagKC3ViC3qqlrJdDk0qFEQFCctIcj60aKBum0jkqA2CbLX2o45",
	"0qI3cKEAk6NsSOoR+g9yFxcEotj6f02iWpF4glWpj0p7bz+l5q4b1ijrpsR0lpFnY0xwKRo+PpysLwO5",
	"RUnbe9fcg9efQSCga02eS/7vt9bL3//+y3HVS/NF3D24XRI1fOcUS7XWvvK67vPr2xu21shMLirxWAFr",
	"ApfZBhSgcFLsu6SSif2EyVjL1owJVbAjRjnLkipnOlYFu7694Rl/ATTB5Mer+dXck74BJRrJF/zT1fzq",
	"k+/NVPqQZ6KopZodjH5o/FwLPNUBW4es9/CmcOa0oWt3qj8LDQ+QgKHPuvBlkWtFscpE01Qy92pm30yA",
	"NAxW9/V/hDVf8P/NDpN3FsfubGzm7o45QGjBL4Tm4CP4af5xCMUvCK56j1jAFw/H+D8sd8uMG1vXvsLj",
	"oQ46LCTK4SA2xk8ZlxS+dGpjWmMfmZLM21b08hz2SnDv6Sp4GrvZvuyslcXZFp3UkqinCUjMh0jEoNsa",
	"eCsmd1axmGJfW4Jt5Auoici4mjGzvbZXvoEEQF9hj48/cB/lXQ2hqIEAjXdUuoCeLfi9cFnqzpF+frIO",
	"cH0IluncXUgEqJtKbwFOzaBWZmziTRgW526JZwfSmaEbXGjEVluaNqx2/RnCI3iX8u0rEIt/TK+ZqKq2",
	"ixsm91Qc452lclbpjVRnuoGl8g8v9k7dtPMKmF63/6LpeHdLwOPDZsb623qAZp/7sCcMa6nKXMH7/Hby",
	"7WAL6W7FOqPtdN6/xAOHafMerThQ1D0Pbe08zkvIn1Y+iPDp2L18Q1f2gpc15MRoPATPjH2sJb25Ru79",
	"se6cdJ05t4igiBVi24GrxagPWXvtmQZY+wR6p3rpv7AuTW2r5wcTqw/Rnktj7E2nRlubwzjd/tNT7RRI",
	"/Ydhorm0t2QEQgkvl/T+9sp+dNcYNP0xOI6v75Oofde78b8Hv5MPuktJfqTsB5k+eO4k8uvV4kvL1v44",
	"yUXFwj7PuMUqvtMWs1nl9kptaPHzfD7nu+XunwAAAP//mwHNSvUTAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
