// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for PostEmployeeAttendanceJSONBodyAttendanceType.
const (
	CheckIn  PostEmployeeAttendanceJSONBodyAttendanceType = "check_in"
	CheckOut PostEmployeeAttendanceJSONBodyAttendanceType = "check_out"
)

// AttendancePeriodRequest defines model for AttendancePeriodRequest.
type AttendancePeriodRequest struct {
	EndDate   openapi_types.Date `json:"end_date"`
	StartDate openapi_types.Date `json:"start_date"`
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// DefaultErrorResponse defines model for DefaultErrorResponse.
type DefaultErrorResponse struct {
	Error struct {
		Message string `json:"message"`
	} `json:"error"`
}

// OvertimeRequest defines model for OvertimeRequest.
type OvertimeRequest struct {
	Description string    `json:"description"`
	EndTime     time.Time `json:"end_time"`
	StartTime   time.Time `json:"start_time"`
}

// PayslipResponse defines model for PayslipResponse.
type PayslipResponse struct {
	BaseSalary      *int    `json:"base_salary,omitempty"`
	OvertimePayment *int    `json:"overtime_payment,omitempty"`
	PayrollId       *string `json:"payroll_id,omitempty"`
	ProratedSalary  *int    `json:"prorated_salary,omitempty"`
	Reimbursements  *[]struct {
		Amount      *int    `json:"amount,omitempty"`
		Date        *string `json:"date,omitempty"`
		Description *string `json:"description,omitempty"`
	} `json:"reimbursements,omitempty"`
	TotalTakeHome *int `json:"total_take_home,omitempty"`
}

// ReimbursementRequest defines model for ReimbursementRequest.
type ReimbursementRequest struct {
	Amount      int                `json:"amount"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
}

// PostAdminPayrollsJSONBody defines parameters for PostAdminPayrolls.
type PostAdminPayrollsJSONBody struct {
	AttendancePeriodId int `json:"attendance_period_id"`
}

// PostEmployeeAttendanceJSONBody defines parameters for PostEmployeeAttendance.
type PostEmployeeAttendanceJSONBody struct {
	AttendanceType PostEmployeeAttendanceJSONBodyAttendanceType `json:"attendance_type"`
}

// PostEmployeeAttendanceJSONBodyAttendanceType defines parameters for PostEmployeeAttendance.
type PostEmployeeAttendanceJSONBodyAttendanceType string

// GetEmployeePayslipParams defines parameters for GetEmployeePayslip.
type GetEmployeePayslipParams struct {
	PayrollId string `form:"payroll_id" json:"payroll_id"`
}

// PostAdminAttendancePeriodsJSONRequestBody defines body for PostAdminAttendancePeriods for application/json ContentType.
type PostAdminAttendancePeriodsJSONRequestBody = AttendancePeriodRequest

// PostAdminPayrollsJSONRequestBody defines body for PostAdminPayrolls for application/json ContentType.
type PostAdminPayrollsJSONRequestBody PostAdminPayrollsJSONBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthRequest

// PostEmployeeAttendanceJSONRequestBody defines body for PostEmployeeAttendance for application/json ContentType.
type PostEmployeeAttendanceJSONRequestBody PostEmployeeAttendanceJSONBody

// PostEmployeeOvertimeJSONRequestBody defines body for PostEmployeeOvertime for application/json ContentType.
type PostEmployeeOvertimeJSONRequestBody = OvertimeRequest

// PostEmployeeReimbursementJSONRequestBody defines body for PostEmployeeReimbursement for application/json ContentType.
type PostEmployeeReimbursementJSONRequestBody = ReimbursementRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xXTW/jNhP+KwTf96iNvd1L4Vu23S5SFGiQFOghMAxGGlvcSKQyHGYhBP7vBUnJ1gdl",
	"K96mN32QM8N5npln+MpTXVZagSLDV6/cpDmUwj9eE4HKhErhFlDq7A6eLRhyvyrUFSBJ8AtBZZtMELjn",
	"rcZSEF9x/yHhVFfAV9wQSrXj+4QbEkhzl+8TjvBsJULGVw/dvcnR6/qwTT9+g5Scl2tL+WS8lTDmu8bM",
	"PY/iswZQiRIiPwfRHFYmR4vTsZhKKwPjYESagjEb0k+gogEhbBFMPrliEFXP3nB3LLxfYStsQV8QNU6H",
	"Ce73+HMJxojdjGS1C8cRDBYGR7FA/3xxfkuYxDUDk6KsSOp4Jh1jnIER8T74r5NkfcueKGObpQf/SS/U",
	"2FlvRW0KWU3j8SgMbIwoBNads0pFsAN0FnSTrU0l6hIUxVdVokZdFBsZL4YKNQqC7KQnBFk+WjRQtk1E",
	"EpQmQvVS26lA2oYwCuE0qPtI7poPAlHU/l2TKDYknmCT615hH/zHzNx1jzXJuTlnOtsTz56xS6nGSOP4",
	"HJUciSG1KKm+d609RP0ZBAK6xuS55N9+a6P8/e+/eBKEwFkKf49h50QV3zvDUm31qO749e0N22pkJhWF",
	"eCyAVYHLbAcKULhV7LuknImDviSsZWvChMpYj1HOs6TCuW6qgl3f3vCEvwCa4PLj1fJq6UlfgRKV5Cv+",
	"6Wp59cl3Zsr9kRciK6VaHJ1+qLyqBZ7qgK1D1kd4kzl32tC12zVUQsMDJGDos858WaRaUVNloqoKmXoz",
	"i28mQBpk1T39H2HLV/x/i6PuLhrRXUwp7r7PAUIL/kNoDv4EPy0/jqH4BcFVb48FfPXQx/9hvV8n3Niy",
	"9BXebOqgw0KiHA5iZ7zGuKTwtTPbpLXpI3OSedsuvTyHgxI8RLoJkfa7WbfIe0IZ2xYpoBmpX45T35yy",
	"Jf1bQbizijU59cUk2E6+gHoLFItXme1dYDuIwPEV+mjcZL5YUJRAgMYHKN1BXAHxhIeRiMuMD9ORdIAZ",
	"dq51PFUXAg1lVega4JTGtGumFG2GGJybAc8KzhlRDSFUotaW5onRfqgR/D4w5VJ6fQVizRvTWyaKou3S",
	"hskD86ZoZilfFHon1Zlqt5T/4Ze9U7fszPjzy/RfdN3MZhF4/LGZsX4WD9Acch/+CcNaqjJX3z6/nXw7",
	"2EK622Ud6Tqd9y/NhqOavEerDRR1lz9buojTHNKnjT9EeHTsXp+bj4cGL+u/Eek7Hp4Z+1hKenON3Ptt",
	"XR10jTi1iKCIZaLuwNViNISsHWvmAdZecN6pXob3p0tT29r5wcTq42nPpbHpTafErM1hMyJOiNmzBayP",
	"atZp1P+lqp0CaXjxizSXdgpGIJTwcknvb0fy3mgxavpTcPTH81nUvhtM9O/B7+iF7VKS94z9INNH15lI",
	"fr1ZfGnZOpSTVBQs/OcJt1g097DVYlG4f7k2tPp5uVzy/Xr/TwAAAP//n1Gk7dMTAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
