// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for PostEmployeeAttendanceJSONBodyAttendanceType.
const (
	CheckIn  PostEmployeeAttendanceJSONBodyAttendanceType = "check_in"
	CheckOut PostEmployeeAttendanceJSONBodyAttendanceType = "check_out"
)

// AdminPayrollSummaryResponse defines model for AdminPayrollSummaryResponse.
type AdminPayrollSummaryResponse struct {
	AttendancePeriod       *AttendancePeriod `json:"attendance_period,omitempty"`
	EmployeesCount         *int              `json:"employees_count,omitempty"`
	PayrollId              *int              `json:"payroll_id,omitempty"`
	PayslipList            *[]PayslipItem    `json:"payslip_list,omitempty"`
	TotalOvertimePay       *int              `json:"total_overtime_pay,omitempty"`
	TotalPayroll           *int              `json:"total_payroll,omitempty"`
	TotalReimbursementsPay *int              `json:"total_reimbursements_pay,omitempty"`
}

// AttendancePeriod defines model for AttendancePeriod.
type AttendancePeriod struct {
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	StartDate *openapi_types.Date `json:"start_date,omitempty"`
}

// AttendancePeriodRequest defines model for AttendancePeriodRequest.
type AttendancePeriodRequest struct {
	EndDate   openapi_types.Date `json:"end_date"`
	StartDate openapi_types.Date `json:"start_date"`
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// DefaultErrorResponse defines model for DefaultErrorResponse.
type DefaultErrorResponse struct {
	Error struct {
		Message string `json:"message"`
	} `json:"error"`
}

// OvertimeRequest defines model for OvertimeRequest.
type OvertimeRequest struct {
	Description string    `json:"description"`
	EndTime     time.Time `json:"end_time"`
	StartTime   time.Time `json:"start_time"`
}

// PayslipItem defines model for PayslipItem.
type PayslipItem struct {
	AttendanceCount       *int    `json:"attendance_count,omitempty"`
	BaseSalary            *int    `json:"base_salary,omitempty"`
	EmployeeId            *int    `json:"employee_id,omitempty"`
	OvertimeCount         *int    `json:"overtime_count,omitempty"`
	OvertimePayment       *int    `json:"overtime_payment,omitempty"`
	ProratedSalary        *int    `json:"prorated_salary,omitempty"`
	ReimbursementsPayment *int    `json:"reimbursements_payment,omitempty"`
	TotalPay              *int    `json:"total_pay,omitempty"`
	Username              *string `json:"username,omitempty"`
}

// PayslipResponse defines model for PayslipResponse.
type PayslipResponse struct {
	AttendanceCount     *int                 `json:"attendance_count,omitempty"`
	BaseSalary          *int                 `json:"base_salary,omitempty"`
	EmployeeId          *int                 `json:"employee_id,omitempty"`
	OvertimePayment     *int                 `json:"overtime_payment,omitempty"`
	OvertimeTotalHours  *int                 `json:"overtime_total_hours,omitempty"`
	PayrollId           *int                 `json:"payroll_id,omitempty"`
	ProratedSalary      *int                 `json:"prorated_salary,omitempty"`
	Reimbursements      *[]ReimbursementItem `json:"reimbursements,omitempty"`
	ReimbursementsTotal *int                 `json:"reimbursements_total,omitempty"`
	TotalTakeHome       *int                 `json:"total_take_home,omitempty"`
	TotalWorkingDays    *int                 `json:"total_working_days,omitempty"`
}

// ReimbursementItem defines model for ReimbursementItem.
type ReimbursementItem struct {
	Amount      *int                `json:"amount,omitempty"`
	Date        *openapi_types.Date `json:"date,omitempty"`
	Description *string             `json:"description,omitempty"`
}

// ReimbursementRequest defines model for ReimbursementRequest.
type ReimbursementRequest struct {
	Amount      int                `json:"amount"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
}

// PostAdminPayrollsJSONBody defines parameters for PostAdminPayrolls.
type PostAdminPayrollsJSONBody struct {
	AttendancePeriodId int `json:"attendance_period_id"`
}

// PostEmployeeAttendanceJSONBody defines parameters for PostEmployeeAttendance.
type PostEmployeeAttendanceJSONBody struct {
	AttendanceType PostEmployeeAttendanceJSONBodyAttendanceType `json:"attendance_type"`
}

// PostEmployeeAttendanceJSONBodyAttendanceType defines parameters for PostEmployeeAttendance.
type PostEmployeeAttendanceJSONBodyAttendanceType string

// PostAdminAttendancePeriodsJSONRequestBody defines body for PostAdminAttendancePeriods for application/json ContentType.
type PostAdminAttendancePeriodsJSONRequestBody = AttendancePeriodRequest

// PostAdminPayrollsJSONRequestBody defines body for PostAdminPayrolls for application/json ContentType.
type PostAdminPayrollsJSONRequestBody PostAdminPayrollsJSONBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthRequest

// PostEmployeeAttendanceJSONRequestBody defines body for PostEmployeeAttendance for application/json ContentType.
type PostEmployeeAttendanceJSONRequestBody PostEmployeeAttendanceJSONBody

// PostEmployeeOvertimeJSONRequestBody defines body for PostEmployeeOvertime for application/json ContentType.
type PostEmployeeOvertimeJSONRequestBody = OvertimeRequest

// PostEmployeeReimbursementJSONRequestBody defines body for PostEmployeeReimbursement for application/json ContentType.
type PostEmployeeReimbursementJSONRequestBody = ReimbursementRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXTY/bNhD9KwTbo7J2mkvh26ZNgy0K1NgU6GFhCLQ0tpiVSGVI7cJY+L8X/JD1SVl2",
	"sgv0ZovD4eO8mTfDF5rIopQChFZ09UJVkkHB7M/btOBizQ4o8/xLVRQMD/egSikUmOUSZQmoOVhjpjWI",
	"lIkE4hKQy9R8/BlhR1f0p0VzxsIfsLg9bVg7+2NEoShzeQBQcSIroY0LfSiBrigXGvaAxqh0iGKeBtdV",
	"zss458p64BoKdQ7N2m2601AYH94rQ2QH+19qlsfyydy3gLhkh/GznZ1HOGWCwItthQoKAyPksEEit18h",
	"0Wb/IG4DKkCkccq0JWknsWCarqj9cHKnNHKxN+6UZqjnms/Bcw/fKnCRf0NYCN8qjpDS1UN7b9ScuhnD",
	"XuksiLdkSj1LbGdZg69SgIIVMLLYQ3OyjBqPYSzB8koSUCrW8hHEKCCEHYLKghY9VB1//d1j8H6HHaty",
	"/QlRYhgmmOXh5wKUYvsZwaoNhwh6hu6gMaB/+yIN8pqCSpCXmsvxSJqMMQ4GiffOfg0m6yV7RjPWm57O",
	"jzpQx+7aVq0pRZ5Q0y1TECuWMwxIWq3JQb09qeLEKW3lNIoXUG6UyDSkk3iGyhl2eJLj8eXpIg5Fe1YP",
	"fJuIT17+ZOWikMkK1ZUd9XJeZjfe+/a2UPvtcW4vNMW4Zo8QZ7LD7MDoWeIjF/s4ZQc1t/kO0Q6ToAhT",
	"P7v9TWvUWWRB7XsbcG1p8078weckzYgpJBVyffhiEsSh/ggMAU2DNP+29t8fNco///2HRm5sNZ7cagM7",
	"07qkR+OYi50c6D+9Xd+RnUSiEpazbQ7Ej49kDwKQGSvyzHVGmuKOSF1aEWEiJZ3sNCdznZujvV6Q2/Ud",
	"jegToHJHvr9Z3ixthZYgWMnpin64Wd58sBOCzuyVF8wM34vm0HduqnaTiXTcGmYtwrvUHCeVtiN7fyJT",
	"1FECSn+UqS3fRArthYOVZc4T62bxVTlKXXFeOsHXWXfs5oDGCuwHJ5v2Br8s3w+p+A3BqEwnC+jqocv/",
	"w+a4iahyz5HTphY7xD8/IqrZXtlZxwSFboxbH1YveHOCua5Nr4/hmYdSQHb7A9vYtpECmhH65TD0/pZ1",
	"0l9Kwn0liI+pLSZG9vwJxCVULF54ejTA9jBCx2fosnGX2mJBVoAG09YeXig3FzEFRCPqujrlKe2HI2oR",
	"01euzXiofkyxTDymLWtdQrzJtYR8Bk38PyJ3hOV5rWuK8BNXIWIqnS1yuefiTH1UOvvLmr2SvrReZ/MT",
	"+wceHabHXpuoyr6iHDWn2Ls1pkg9xxFTETa+rXgb2ly4a7OW2E/H/ZPf0Ojva4iTKw7zbK8KgzjJIHmM",
	"7SXcT1nplgCF3pk9h9cp1kizaC5PVLUtuL64Rr7Ybe3OYaQrqRBBaJKyQ4uumqM+ZfUgMI+w+mn6SvXS",
	"f/leG9raz3cGVja3PRdGr0dne0AdSK+j/78u0H9CjkhLPTUiaOTwdI3y1yNspxUPJD9ERnecnZXY970J",
	"+DWye/SBc22Kd5x9Z54Pxv+R+Fq3+FQnab+ZJCwnbp1GtMLcv1tWi0Vu1jKp9OrX5XJJj5vjfwEAAP//",
	"HWwfCLEXAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
