// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asyauqi15/payslip-system/internal/repository (interfaces: PayslipRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_payslip_repository.go -package=mock github.com/asyauqi15/payslip-system/internal/repository PayslipRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/asyauqi15/payslip-system/internal/entity"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPayslipRepository is a mock of PayslipRepository interface.
type MockPayslipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPayslipRepositoryMockRecorder
	isgomock struct{}
}

// MockPayslipRepositoryMockRecorder is the mock recorder for MockPayslipRepository.
type MockPayslipRepositoryMockRecorder struct {
	mock *MockPayslipRepository
}

// NewMockPayslipRepository creates a new mock instance.
func NewMockPayslipRepository(ctrl *gomock.Controller) *MockPayslipRepository {
	mock := &MockPayslipRepository{ctrl: ctrl}
	mock.recorder = &MockPayslipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayslipRepository) EXPECT() *MockPayslipRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPayslipRepository) Create(ctx context.Context, o *entity.Payslip, tx *gorm.DB) (*entity.Payslip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o, tx)
	ret0, _ := ret[0].(*entity.Payslip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPayslipRepositoryMockRecorder) Create(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPayslipRepository)(nil).Create), ctx, o, tx)
}

// FindByID mocks base method.
func (m *MockPayslipRepository) FindByID(ctx context.Context, i uint, tx *gorm.DB) (*entity.Payslip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, i, tx)
	ret0, _ := ret[0].(*entity.Payslip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPayslipRepositoryMockRecorder) FindByID(ctx, i, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPayslipRepository)(nil).FindByID), ctx, i, tx)
}

// FindByTemplate mocks base method.
func (m *MockPayslipRepository) FindByTemplate(ctx context.Context, t *entity.Payslip, tx *gorm.DB) ([]entity.Payslip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTemplate", ctx, t, tx)
	ret0, _ := ret[0].([]entity.Payslip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTemplate indicates an expected call of FindByTemplate.
func (mr *MockPayslipRepositoryMockRecorder) FindByTemplate(ctx, t, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTemplate", reflect.TypeOf((*MockPayslipRepository)(nil).FindByTemplate), ctx, t, tx)
}

// FindOneByTemplate mocks base method.
func (m *MockPayslipRepository) FindOneByTemplate(ctx context.Context, o *entity.Payslip, tx *gorm.DB) (*entity.Payslip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByTemplate", ctx, o, tx)
	ret0, _ := ret[0].(*entity.Payslip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByTemplate indicates an expected call of FindOneByTemplate.
func (mr *MockPayslipRepositoryMockRecorder) FindOneByTemplate(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByTemplate", reflect.TypeOf((*MockPayslipRepository)(nil).FindOneByTemplate), ctx, o, tx)
}

// Save mocks base method.
func (m *MockPayslipRepository) Save(ctx context.Context, o *entity.Payslip, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, o, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPayslipRepositoryMockRecorder) Save(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPayslipRepository)(nil).Save), ctx, o, tx)
}

// Updates mocks base method.
func (m *MockPayslipRepository) Updates(ctx context.Context, o *entity.Payslip, u entity.Payslip, tx *gorm.DB) (*entity.Payslip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, o, u, tx)
	ret0, _ := ret[0].(*entity.Payslip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Updates indicates an expected call of Updates.
func (mr *MockPayslipRepositoryMockRecorder) Updates(ctx, o, u, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockPayslipRepository)(nil).Updates), ctx, o, u, tx)
}
