// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asyauqi15/payslip-system/internal/repository (interfaces: PayrollRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_payroll_repository.go -package=mock github.com/asyauqi15/payslip-system/internal/repository PayrollRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/asyauqi15/payslip-system/internal/entity"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPayrollRepository is a mock of PayrollRepository interface.
type MockPayrollRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPayrollRepositoryMockRecorder
	isgomock struct{}
}

// MockPayrollRepositoryMockRecorder is the mock recorder for MockPayrollRepository.
type MockPayrollRepositoryMockRecorder struct {
	mock *MockPayrollRepository
}

// NewMockPayrollRepository creates a new mock instance.
func NewMockPayrollRepository(ctrl *gomock.Controller) *MockPayrollRepository {
	mock := &MockPayrollRepository{ctrl: ctrl}
	mock.recorder = &MockPayrollRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayrollRepository) EXPECT() *MockPayrollRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPayrollRepository) Create(ctx context.Context, o *entity.Payroll, tx *gorm.DB) (*entity.Payroll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o, tx)
	ret0, _ := ret[0].(*entity.Payroll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPayrollRepositoryMockRecorder) Create(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPayrollRepository)(nil).Create), ctx, o, tx)
}

// FindByID mocks base method.
func (m *MockPayrollRepository) FindByID(ctx context.Context, i uint, tx *gorm.DB) (*entity.Payroll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, i, tx)
	ret0, _ := ret[0].(*entity.Payroll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPayrollRepositoryMockRecorder) FindByID(ctx, i, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPayrollRepository)(nil).FindByID), ctx, i, tx)
}

// FindByTemplate mocks base method.
func (m *MockPayrollRepository) FindByTemplate(ctx context.Context, t *entity.Payroll, tx *gorm.DB) ([]entity.Payroll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTemplate", ctx, t, tx)
	ret0, _ := ret[0].([]entity.Payroll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTemplate indicates an expected call of FindByTemplate.
func (mr *MockPayrollRepositoryMockRecorder) FindByTemplate(ctx, t, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTemplate", reflect.TypeOf((*MockPayrollRepository)(nil).FindByTemplate), ctx, t, tx)
}

// FindOneByTemplate mocks base method.
func (m *MockPayrollRepository) FindOneByTemplate(ctx context.Context, o *entity.Payroll, tx *gorm.DB) (*entity.Payroll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByTemplate", ctx, o, tx)
	ret0, _ := ret[0].(*entity.Payroll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByTemplate indicates an expected call of FindOneByTemplate.
func (mr *MockPayrollRepositoryMockRecorder) FindOneByTemplate(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByTemplate", reflect.TypeOf((*MockPayrollRepository)(nil).FindOneByTemplate), ctx, o, tx)
}

// Save mocks base method.
func (m *MockPayrollRepository) Save(ctx context.Context, o *entity.Payroll, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, o, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPayrollRepositoryMockRecorder) Save(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPayrollRepository)(nil).Save), ctx, o, tx)
}

// Updates mocks base method.
func (m *MockPayrollRepository) Updates(ctx context.Context, o *entity.Payroll, u entity.Payroll, tx *gorm.DB) (*entity.Payroll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, o, u, tx)
	ret0, _ := ret[0].(*entity.Payroll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Updates indicates an expected call of Updates.
func (mr *MockPayrollRepositoryMockRecorder) Updates(ctx, o, u, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockPayrollRepository)(nil).Updates), ctx, o, u, tx)
}
