// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asyauqi15/payslip-system/internal/repository (interfaces: ReimbursementRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_reimbursement_repository.go -package=mock github.com/asyauqi15/payslip-system/internal/repository ReimbursementRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/asyauqi15/payslip-system/internal/entity"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockReimbursementRepository is a mock of ReimbursementRepository interface.
type MockReimbursementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReimbursementRepositoryMockRecorder
	isgomock struct{}
}

// MockReimbursementRepositoryMockRecorder is the mock recorder for MockReimbursementRepository.
type MockReimbursementRepositoryMockRecorder struct {
	mock *MockReimbursementRepository
}

// NewMockReimbursementRepository creates a new mock instance.
func NewMockReimbursementRepository(ctrl *gomock.Controller) *MockReimbursementRepository {
	mock := &MockReimbursementRepository{ctrl: ctrl}
	mock.recorder = &MockReimbursementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReimbursementRepository) EXPECT() *MockReimbursementRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReimbursementRepository) Create(ctx context.Context, o *entity.Reimbursement, tx *gorm.DB) (*entity.Reimbursement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o, tx)
	ret0, _ := ret[0].(*entity.Reimbursement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockReimbursementRepositoryMockRecorder) Create(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReimbursementRepository)(nil).Create), ctx, o, tx)
}

// FindByID mocks base method.
func (m *MockReimbursementRepository) FindByID(ctx context.Context, i uint, tx *gorm.DB) (*entity.Reimbursement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, i, tx)
	ret0, _ := ret[0].(*entity.Reimbursement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockReimbursementRepositoryMockRecorder) FindByID(ctx, i, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockReimbursementRepository)(nil).FindByID), ctx, i, tx)
}

// FindByTemplate mocks base method.
func (m *MockReimbursementRepository) FindByTemplate(ctx context.Context, t *entity.Reimbursement, tx *gorm.DB) ([]entity.Reimbursement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTemplate", ctx, t, tx)
	ret0, _ := ret[0].([]entity.Reimbursement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTemplate indicates an expected call of FindByTemplate.
func (mr *MockReimbursementRepositoryMockRecorder) FindByTemplate(ctx, t, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTemplate", reflect.TypeOf((*MockReimbursementRepository)(nil).FindByTemplate), ctx, t, tx)
}

// FindOneByTemplate mocks base method.
func (m *MockReimbursementRepository) FindOneByTemplate(ctx context.Context, o *entity.Reimbursement, tx *gorm.DB) (*entity.Reimbursement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByTemplate", ctx, o, tx)
	ret0, _ := ret[0].(*entity.Reimbursement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByTemplate indicates an expected call of FindOneByTemplate.
func (mr *MockReimbursementRepositoryMockRecorder) FindOneByTemplate(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByTemplate", reflect.TypeOf((*MockReimbursementRepository)(nil).FindOneByTemplate), ctx, o, tx)
}

// Save mocks base method.
func (m *MockReimbursementRepository) Save(ctx context.Context, o *entity.Reimbursement, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, o, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockReimbursementRepositoryMockRecorder) Save(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockReimbursementRepository)(nil).Save), ctx, o, tx)
}

// Updates mocks base method.
func (m *MockReimbursementRepository) Updates(ctx context.Context, o *entity.Reimbursement, u entity.Reimbursement, tx *gorm.DB) (*entity.Reimbursement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, o, u, tx)
	ret0, _ := ret[0].(*entity.Reimbursement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Updates indicates an expected call of Updates.
func (mr *MockReimbursementRepositoryMockRecorder) Updates(ctx, o, u, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockReimbursementRepository)(nil).Updates), ctx, o, u, tx)
}
