// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asyauqi15/payslip-system/internal/repository (interfaces: OvertimeRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_overtime_repository.go -package=mock github.com/asyauqi15/payslip-system/internal/repository OvertimeRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/asyauqi15/payslip-system/internal/entity"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockOvertimeRepository is a mock of OvertimeRepository interface.
type MockOvertimeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOvertimeRepositoryMockRecorder
	isgomock struct{}
}

// MockOvertimeRepositoryMockRecorder is the mock recorder for MockOvertimeRepository.
type MockOvertimeRepositoryMockRecorder struct {
	mock *MockOvertimeRepository
}

// NewMockOvertimeRepository creates a new mock instance.
func NewMockOvertimeRepository(ctrl *gomock.Controller) *MockOvertimeRepository {
	mock := &MockOvertimeRepository{ctrl: ctrl}
	mock.recorder = &MockOvertimeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOvertimeRepository) EXPECT() *MockOvertimeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOvertimeRepository) Create(ctx context.Context, o *entity.Overtime, tx *gorm.DB) (*entity.Overtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o, tx)
	ret0, _ := ret[0].(*entity.Overtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOvertimeRepositoryMockRecorder) Create(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOvertimeRepository)(nil).Create), ctx, o, tx)
}

// FindByID mocks base method.
func (m *MockOvertimeRepository) FindByID(ctx context.Context, i uint, tx *gorm.DB) (*entity.Overtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, i, tx)
	ret0, _ := ret[0].(*entity.Overtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOvertimeRepositoryMockRecorder) FindByID(ctx, i, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOvertimeRepository)(nil).FindByID), ctx, i, tx)
}

// FindByTemplate mocks base method.
func (m *MockOvertimeRepository) FindByTemplate(ctx context.Context, t *entity.Overtime, tx *gorm.DB) ([]entity.Overtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTemplate", ctx, t, tx)
	ret0, _ := ret[0].([]entity.Overtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTemplate indicates an expected call of FindByTemplate.
func (mr *MockOvertimeRepositoryMockRecorder) FindByTemplate(ctx, t, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTemplate", reflect.TypeOf((*MockOvertimeRepository)(nil).FindByTemplate), ctx, t, tx)
}

// FindOneByTemplate mocks base method.
func (m *MockOvertimeRepository) FindOneByTemplate(ctx context.Context, o *entity.Overtime, tx *gorm.DB) (*entity.Overtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByTemplate", ctx, o, tx)
	ret0, _ := ret[0].(*entity.Overtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByTemplate indicates an expected call of FindOneByTemplate.
func (mr *MockOvertimeRepositoryMockRecorder) FindOneByTemplate(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByTemplate", reflect.TypeOf((*MockOvertimeRepository)(nil).FindOneByTemplate), ctx, o, tx)
}

// Save mocks base method.
func (m *MockOvertimeRepository) Save(ctx context.Context, o *entity.Overtime, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, o, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOvertimeRepositoryMockRecorder) Save(ctx, o, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOvertimeRepository)(nil).Save), ctx, o, tx)
}

// Updates mocks base method.
func (m *MockOvertimeRepository) Updates(ctx context.Context, o *entity.Overtime, u entity.Overtime, tx *gorm.DB) (*entity.Overtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, o, u, tx)
	ret0, _ := ret[0].(*entity.Overtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Updates indicates an expected call of Updates.
func (mr *MockOvertimeRepositoryMockRecorder) Updates(ctx, o, u, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockOvertimeRepository)(nil).Updates), ctx, o, u, tx)
}
