openapi: 3.0.3
info:
  title: Payslip API
  version: 1.0.0
  description: API for scalable payslip generation with attendance, overtime, and reimbursement

servers:
  - url: http://localhost:8000
    description: Local server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string

    AuthResponse:
      type: object
      required: [access_token, refresh_token]
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    AttendancePeriodRequest:
      type: object
      required: [start_date, end_date]
      properties:
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date

    OvertimeRequest:
      type: object
      required: [start_time, end_time, description]
      properties:
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        description:
          type: string

    ReimbursementRequest:
      type: object
      required: [date, amount, description]
      properties:
        date:
          type: string
          format: date
        amount:
          type: integer
        description:
          type: string

    AttendancePeriod:
      type: object
      properties:
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date

    ReimbursementItem:
      type: object
      properties:
        date:
          type: string
          format: date
        amount:
          type: integer
        description:
          type: string

    PayslipItem:
      type: object
      properties:
        employee_id:
          type: integer
        username:
          type: string
        base_salary:
          type: integer
        attendance_count:
          type: integer
        overtime_count:
          type: integer
        prorated_salary:
          type: integer
        overtime_payment:
          type: integer
        reimbursements_payment:
          type: integer
        total_pay:
          type: integer

    AdminPayrollSummaryResponse:
      type: object
      properties:
        payroll_id:
          type: integer
        attendance_period:
          $ref: "#/components/schemas/AttendancePeriod"
        employees_count:
          type: integer
        total_payroll:
          type: integer
        total_reimbursements_pay:
          type: integer
        total_overtime_pay:
          type: integer
        payslip_list:
          type: array
          items:
            $ref: "#/components/schemas/PayslipItem"

    PayslipResponse:
      type: object
      properties:
        payroll_id:
          type: integer
        attendance_period:
          $ref: "#/components/schemas/AttendancePeriod"
        employee_id:
          type: integer
        base_salary:
          type: integer
        attendance_count:
          type: integer
        total_working_days:
          type: integer
        prorated_salary:
          type: integer
        overtime_total_hours:
          type: integer
        overtime_payment:
          type: integer
        reimbursements:
          type: array
          items:
            $ref: "#/components/schemas/ReimbursementItem"
        reimbursements_total:
          type: integer
        total_take_home:
          type: integer

    DefaultErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - message
          properties:
            message:
              type: string

paths:
  /auth/login:
    post:
      tags: [auth]
      summary: Login as employee or admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequest"
      responses:
        200:
          description: Login success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /admin/attendance-periods:
    post:
      tags: [admin]
      summary: Create attendance period
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttendancePeriodRequest"
      responses:
        201:
          description: Created

  /admin/payrolls:
    post:
      tags: [admin]
      summary: Run payroll for a given period
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [attendance_period_id]
              properties:
                attendance_period_id:
                  type: integer
      responses:
        200:
          description: Payroll generated

  /admin/payrolls/{id}:
    get:
      tags: [admin]
      summary: Get summary of all payslips in payroll
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Summary generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdminPayrollSummaryResponse"

  /employee/attendance:
    post:
      tags: [employee]
      summary: Submit attendance for current day
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [attendance_type]
              properties:
                attendance_type:
                  type: string
                  enum: [check_in, check_out]
      responses:
        201:
          description: Attendance submitted

  /employee/overtime:
    post:
      tags: [employee]
      summary: Submit overtime
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OvertimeRequest"
      responses:
        201:
          description: Overtime submitted

  /employee/reimbursement:
    post:
      tags: [employee]
      summary: Submit reimbursement
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReimbursementRequest"
      responses:
        201:
          description: Reimbursement submitted

  /employee/payroll/{id}:
    get:
      tags: [employee]
      summary: Get payslip for a given payroll
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Payslip retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PayslipResponse"
